=== Elvis020/Elvis-Documentary/Labs/Week_6/Day_1/XML101/src/com/elvis/training_labs_personal/expenses.dtd
<!ELEMENT expenses (bags,watches,shirts,shoes) >
<!ELEMENT bags (travelling_Bag,school_Bag)>
<!ELEMENT shirts (with_cuffs,without_cuffs) >
<!ELEMENT shoes (lofers,desert_boot)>
<!ELEMENT travelling_Bag (#PCDATA)>
<!ELEMENT school_Bag (#PCDATA)>
<!ELEMENT with_cuffs (#PCDATA)>
<!ELEMENT without_cuffs (#PCDATA)>
<!ELEMENT watches (#PCDATA)>
<!ELEMENT lofers (#PCDATA)>
<!ELEMENT desert_boot (#PCDATA)>

=== Elvis020/Elvis-Documentary/Labs/Week_6/Day_1/XML101/src/com/elvis/training_labs_personal/ExpensesMarkUp.xml
<?xml version="1.0" ?>
<!DOCTYPE expenses SYSTEM "expenses.dtd">

<expenses>
    <bags>
        <travelling_Bag/>
        <school_Bag/>
    </bags>
    <watches/>
    <shirts>
        <with_cuffs/>
        <without_cuffs/>
    </shirts>
    <shoes>
        <lofers/>
        <desert_boot/>
    </shoes>
</expenses>
