=== Elvis020/Elvis-Documentary/Labs/Week_6/Day_1/XML101/src/com/elvis/training_labs_personal/file_System.dtd
<!ELEMENT file (type, permissions,hard-links,file-owner,file-group,size,date,name)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT owner (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT permissions (owner,group,user)>
<!ELEMENT hard-links (#PCDATA)>
<!ELEMENT file-owner (#PCDATA)>
<!ELEMENT file-group (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT name (#PCDATA)>

=== Elvis020/Elvis-Documentary/Labs/Week_6/Day_1/XML101/src/com/elvis/training_labs_personal/File.xml
<?xml version="1.0" ?>
<!-- <!DOCTYPE file SYSTEM "file_System.dtd"> -->
<!ELEMENT file (type, permissions,hard-links,file-owner,file-group,size,date,name)>




<!ELEMENT type (#PCDATA)>
<!ELEMENT owner (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT permissions (owner,group,user)>
<!ELEMENT hard-links (#PCDATA)>
<!ELEMENT file-owner (#PCDATA)>
<!ELEMENT file-group (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT name (#PCDATA)>


<file>

    <type>d</type>
    <permissions>
        <owner>rwx</owner>
        <group>rwx</group>
        <user>r-x</user>
    </permissions>
    <hard-links>2</hard-links>
    <file-owner>evad</file-owner>
    <file-group>cc3591</file-group>
    <size>8192</size>
    <date>Oct-29-2001</date>
    <name>play</name>


</file>



-type   -permissions      -hard-links   -file-owner    -file-group   -size    -date             -file-name
d       rwx | rwx | r-x       2          evad           cc3591       8192     Oct 29  2001      play
